### ISSUE TITLE
Submit your week1 slides here

### ISSUE THREAD

**Issue by rmorros** [MCV-2019-M1-Project/deliverables#1]
Submit your week 1 report here by publishing the link to your public GDrive slides.

Deadline Sunday 6th October 2019, 18:00h

**Comment by EddieMG** [comment]
### **TEAM 8**
https://docs.google.com/presentation/d/15h7x8rBCcCCggzfWrJ9-38Dluv39hIhlsJ9DRXGnaNI/edit?usp=sharing

**Comment by RogerCasalsVilardell** [comment]
**TEAM 2**

https://docs.google.com/presentation/d/1rIp77oCnP0knwRqvzISK7m5l87J_61BQ1Xm4zQ8qjKA/edit?usp=sharing

**Comment by sergiocasaspastor** [comment]
**TEAM 4**

https://drive.google.com/file/d/12lkVgFkJs0ZWDThkyyTrXcP2W6iZ5FQz/view?usp=sharing

**Comment by claragarciamoll** [comment]
**TEAM 7**

https://docs.google.com/presentation/d/1HovXQxUjR-t87t8XJhDWgLfpe_0ok8jd3SxT5fKQh04/edit?usp=sharing

**Comment by lunasara** [comment]
https://docs.google.com/presentation/d/1wjyoy7b-XISdpXI_DEEpitdnEHr5_5SYa9aRyoqbZg8/edit#slide=id.g62edf1f3a5_0_379

**Comment by lunasara** [comment]
https://docs.google.com/presentation/d/1wjyoy7b-XISdpXI_DEEpitdnEHr5_5SYa9aRyoqbZg8/edit?usp=sharing

**Comment by liulisixin** [comment]
#Team5
Version 1: 
https://docs.google.com/presentation/d/18dr6oVh75zpBQS97x1-PPmriRh8Qp1bBrJxeXBcchsc/edit?usp=sharing
Version 2: https://docs.google.com/presentation/d/1YjOL6GkGBlDoJkh_Rlx60HNPY2DZD0GO3CF8gc41lWk/edit?usp=sharing
Version1 uses the template, and version2 is a brief version.

**Comment by lunasara** [comment]
#### Team 3

https://docs.google.com/presentation/d/1wjyoy7b-XISdpXI_DEEpitdnEHr5_5SYa9aRyoqbZg8/edit?usp=sharing

**Comment by halops** [comment]
**Team 6**
https://docs.google.com/presentation/d/10ocJ_3BMaB-4R0t3L8irNAAjJv8OTbjd2GbGkN05ick/edit?usp=sharing

**Comment by mrfarge** [comment]
**Team 1**

https://docs.google.com/presentation/d/1jMxan5liAz8V2teiQkkrxn6u7ZwLRvEZePCzZuXk1cQ/edit?usp=sharing
