### ISSUE TITLE
Submit your week2 slides here

### ISSUE THREAD

**Issue by paudom** [MCV-2019-M1-Project/deliverables#2]
Team2: https://docs.google.com/presentation/d/1GfVI2ERUKtSXUCqJXar7PRIZ9XaeUNGCDj9nbjEp1dM/edit#slide=id.g620d675f63_0_0

**Comment by lunasara** [comment]
Team 3
https://docs.google.com/presentation/d/1BM1VSg8Pc3xY9fwnuSdx3E7vR24Hg3XfRU-PFGtIkpc/edit?usp=sharing

**Comment by polalbacar** [comment]
**Team 7**
https://docs.google.com/presentation/d/18csME3lXKaByBSQ6WU2nelZg1sgbhKC4eMp8kBcCQcY/edit?usp=sharing

**Comment by brugues** [comment]
**Team 4**
https://drive.google.com/file/d/1HnHFoQNfw116Y6bx3lS0ndQQlz-D3-SC/view?usp=sharing

**Comment by halops** [comment]
**Team 6**
https://docs.google.com/presentation/d/1mfOv-EER-uEtqRhs3B572BHTm5OiDH5wfJKaqtWlvqQ/edit?usp=sharing

**Comment by mariavila** [comment]
Team 1:
https://docs.google.com/presentation/d/10fOZTKlkKG-RaotgATu4RqGsvAutjOLyjPPjDip8a0g/edit?usp=sharing

**Comment by Marc-Oros** [comment]
Team 8:
https://docs.google.com/presentation/d/18XEMWiRstBkBHIq_1st3xS22oE2k0cV9z5C7jQhBgvg/edit#slide=id.g64048a3679_4_89
