### ISSUE TITLE
Submit your week3 slides here

### ISSUE THREAD

**Issue by rmorros** [MCV-2019-M1-Project/deliverables#3]

**Comment by lunasara** [comment]
Team 3
https://docs.google.com/presentation/d/13CqbZv3tugSobAySxskoX9gMDnYEtlA_wjnomIIoCVo/edit?usp=sharing

**Comment by sergiocasaspastor** [comment]
Team 4
https://drive.google.com/open?id=1oaOwgYm6ZvufTF3qXziYM_mJLN3E2yK4jtHCWR7Y84Q

**Comment by halops** [comment]
Team 6
https://docs.google.com/presentation/d/1YsjlPmrcw40ugDpnd8D0BKabig2meOe1SmbehCf3Kos/edit?usp=sharing

**Comment by RogerCasalsVilardell** [comment]
Team 2
https://docs.google.com/presentation/d/1h74FsmsQjNDSXCUB4Szm-vnASix99uLw-pAGuiYlN7c/edit?usp=sharing

**Comment by mariavila** [comment]
Team 1:
https://docs.google.com/presentation/d/1iQqdygW2txRkpxgv7k90_LXnf7Wec1-ntyCApUhvmuo/edit?usp=sharing

**Comment by polalbacar** [comment]
**Team 7**
https://docs.google.com/presentation/d/1JfnHEKhElrsmhco6CmtIQIwaby9VaU2mWBYX5IkzhfA/edit?usp=sharing

**Comment by Marc-Oros** [comment]
Team 8
https://docs.google.com/presentation/d/1CfmkjaqfCpb2TBLgbqWdWwuzO6ReuK4Ya9kXDEYVpHg/edit#slide=id.g7077e5d894_0_21
