### ISSUE TITLE
Week4 slides

### ISSUE THREAD

**Issue by RogerCasalsVilardell** [MCV-2019-M1-Project/deliverables#4]
Team2
https://docs.google.com/presentation/d/1TEO4FX-eXIGj8EhUf9-g3Sv-mpBuWwm0ZYt5EVxZN-g/edit?usp=sharing

**Comment by lunasara** [comment]
Team 3
https://docs.google.com/presentation/d/1LmotPqC5b8IesmguXBNbSidiHQB60ASpfUuZKu64Kmo/edit?usp=sharing
