### ISSUE TITLE
Submit your week4 slides here

### ISSUE THREAD

**Issue by liulisixin** [MCV-2019-M1-Project/deliverables#5]

**Comment by biswassanket** [comment]
Team 4 Slides for Week 4: https://docs.google.com/presentation/d/1ZlTSNRCFIt-Ky5NMtLSZTdzQ9AvTgL2f-0tmsZLWF-M/edit?usp=sharing

**Comment by halops** [comment]
Team 6
https://docs.google.com/presentation/d/1mMqAefWdPkgSANp4ICj9hUaKGXME7Xq0JqVrjuX3BZI/edit?usp=sharing

**Comment by Marc-Oros** [comment]
Team 8:
https://docs.google.com/presentation/d/1MaL4sKUvm5znW7d74Jv32lkCrlDE3uKEW7z_ixmkROo/edit?usp=sharing

**Comment by claragarciamoll** [comment]
https://docs.google.com/presentation/d/19tH42cq_wK3HL8eUuYc36tGIYAEwX-2zXXezjc2Uok8/edit?usp=sharing

**Comment by hermesvf** [comment]
Team 1 slides:
https://docs.google.com/presentation/d/1NY7uO6_PYQ5ccw11ZamkkpB91DmuQOZvJQrVFdjkHPo/edit#slide=id.g70793609c3_0_974

**Comment by lunasara** [comment]
Team 3
https://docs.google.com/presentation/d/1LmotPqC5b8IesmguXBNbSidiHQB60ASpfUuZKu64Kmo/edit?usp=sharing

**Comment by paudom** [comment]
Team2
https://docs.google.com/presentation/d/1TEO4FX-eXIGj8EhUf9-g3Sv-mpBuWwm0ZYt5EVxZN-g/edit?usp=sharing

**Comment by paudom** [comment]
Team2
https://docs.google.com/presentation/d/1TEO4FX-eXIGj8EhUf9-g3Sv-mpBuWwm0ZYt5EVxZN-g/edit?usp=sharing
